# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuidedOfflineEditingPlugin project_context_manager.py
                                 A QGIS plugin
 Extend the built-in Offline Editing Plugin providing automated processes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-06-08
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Yann Voté
        email                : ygversil@lilo.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from contextlib import contextmanager

from qgis.core import Qgis, QgsProject, QgsMessageLog


@contextmanager
def transactional_project(iface):
    """Context manager returning a ``QgsProject`` instance and saves it on exit
    if no error occured.

    The project is also saved before the context manager returns its instance.

    Implementation detail: we need to reload the project with
    ``iface.addProject()`` after saving it. Otherwise, if the user clicks on
    the save icon in QGIS UI, a warning will be shown indicating that the file
    has been modified on disk after it has been opened by QGIS.
    """
    proj = QgsProject.instance()
    project_saved = proj.write()
    if not project_saved:
        QgsMessageLog.logMessage('GuidedOfflineEditing: project has not been '
                                 'saved before transaction.'
                                 'Extensions',
                                 Qgis.Warning)
    try:
        yield proj
    except Exception as exc:
        QgsMessageLog.logMessage('GuidedOfflineEditing: {}'.format(str(exc)),
                                 'Extensions',
                                 Qgis.Critical)
        QgsMessageLog.logMessage('GuidedOfflineEditing: an error occured, '
                                 "project not saved.",
                                 'Extensions',
                                 Qgis.Critical)
    finally:
        project_saved = proj.write()
        if not project_saved:
            QgsMessageLog.logMessage('GuidedOfflineEditing: project has not '
                                     'been saved after transaction.'
                                     'Extensions',
                                     Qgis.Warning)
        # XXX: better way to avoid warning if the user click save ?
        iface.addProject(proj.fileName())
